### ISSUE TITLE
javascript errors on requests pages

### ISSUE THREAD

**Issue by uberweb** [Slack06/yadg#9]
not a big issue, maybe just disable it from running on the requests listing page.

first error on `api_token_input.value = api_token;` as that input field does not exist.
was able to fix that but then got an error
`button.addEventListener('click',function(e) { e.preventDefault(); yadg.makeRequest();},false);`

works fine as is on requests.php?action=new though

**Comment by Slack06** [comment]
This should be fixed with [this commit](https://github.com/Slack06/yadg-userscript/commit/44a4636f8c4b55d710319ccb53d4cb897def036a). The next version of the user script will contain the fix.

Please report issues with the user script in [this repository](https://github.com/Slack06/yadg-userscript) in the future. Thanks!

**Comment by uberweb** [comment]
cool. thanks for the speedy response.
